<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-JobPulse.Worker-7aafda22-80c1-4619-9aa8-3003dcb6e0cb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Keys\firebase.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Keys\firebase.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobPulse.Data\JobPulse.Data.csproj" />
    <ProjectReference Include="..\JobPulse.Service\JobPulse.Service.csproj" />
  </ItemGroup>
</Project>
